"""
Utility functions for neurotransmitter analysis
Author: Yuan Zhang
Date: 2025-07-25

This module provides helper functions for:
  - Generating surrogate brain maps using spatial null models (Burt2020 or Moran).
  - Computing adjusted R² values for linear regression models.
  - Performing spin-tests (permutation-based significance testing) for regression results.
"""


import threadpoolctl
from brainsmash import mapgen
from brainspace.null_models import moran
import numpy as np
from sklearn.linear_model import LinearRegression
from scipy.stats import pearsonr
from scipy.spatial.distance import squareform, pdist

# Project directory (used for saving outputs)
project_dir = '/Users/zhangyuan/Google Drive/2023_math_reading_neurotransmitter/GitHub/'

# Seed for reproducibility in surrogate generation
seed = 10000

# Number of parallel workers for surrogate generation
n_proc = 4


def make_surrogates(data, dist_fname, spatnull, n_perm):
    """
    Generates surrogate brain maps using spatial null models.

    Parameters
    ----------
    data : array-like, shape (N,)
        Input brain data (e.g., GMV weights) to generate surrogates for.
    dist_fname : str
        Path to the distance matrix (e.g., BNA_distmat_218.txt).
        Distance matrix should be square and symmetric with shape (N, N).
    spatnull : {'burt2020', 'moran'}
        Spatial null model to use:
          - 'burt2020': Burt et al. 2020 method (uses brainsmash).
          - 'moran': Moran randomization model (uses brainspace).
    n_perm : int
        Number of surrogate maps to generate.

    Returns
    -------
    surrogates : ndarray, shape (N, n_perm)
        Surrogate brain maps. Each column is one surrogate permutation.
    """

    if spatnull not in ('burt2020', 'moran'):
        raise ValueError(f'Cannot make surrogates for null method {spatnull}')

    # Convert input to NumPy array
    darr = np.asarray(data)

    # Load distance matrix
    dist = np.loadtxt(dist_fname)

    # Pre-allocate surrogate matrix
    surrogates = np.zeros((len(data), n_perm))

    if spatnull == 'burt2020':
        # Burt et al. 2020 null model
        # Uses brainsmash mapgen for spatial autocorrelation-preserving surrogates
        surrogates = mapgen.Base(darr, dist, seed=seed, n_jobs=n_proc)(n_perm).T

    elif spatnull == 'moran':
        # Moran null model (joint randomization)
        mrs = moran.MoranRandomization(joint=True, n_rep=n_perm, tol=1e-6, random_state=seed)
        with threadpoolctl.threadpool_limits(limits=n_proc): # Limit thread usage
            np.fill_diagonal(dist, 1) # Prevent division by zero on the diagonal
            dist **= -1 # Invert distances (closer points get higher weight)
            surrogates = mrs.fit(dist).randomize(darr).T

    # Save generated surrogates to disk (for reproducibility/debugging)
    outputf = project_dir + 'scripts/spin/surrogatebrainmap_' + spatnull + '_nperm' + str(n_perm) + '_seed' + str(seed) + '.txt'
    np.savetxt(outputf, surrogates)

    return surrogates


def get_reg_r_sq(X, y):
    """
        Compute adjusted R² and regression coefficients using linear regression.

        Parameters
        ----------
        X : ndarray, shape (N, P)
            Predictor matrix (e.g., receptor data).
        y : ndarray, shape (N,)
            Target vector (e.g., brain-behavior association map).

        Returns
        -------
        adjusted_r_squared : float
            Adjusted R² value of the regression model.
        lin_reg.coef_ : ndarray
            Regression coefficients (one per predictor in X).
        """

    lin_reg = LinearRegression()
    lin_reg.fit(X, y)

    # Predictions
    yhat = lin_reg.predict(X)

    # Compute R² and adjusted R²
    SS_Residual = sum((y - yhat) ** 2)
    SS_Total = sum((y - np.mean(y)) ** 2)
    r_squared = 1 - (float(SS_Residual)) / SS_Total
    adjusted_r_squared = 1 - (1 - r_squared) * \
        (len(y) - 1) / (len(y) - X.shape[1] - 1)

    return adjusted_r_squared, lin_reg.coef_


def get_reg_r_pval(X, y, surrogates):
    """
    Compute spin-test p-value for the regression model.

    The empirical adjusted R² is compared against R² values
    computed on surrogate data.

    Parameters
    ----------
    X : ndarray, shape (N, P)
        Predictor matrix (e.g., receptor data).
    y : ndarray, shape (N,)
        Target vector (e.g., brain-behavior association map).
    surrogates : ndarray, shape (N, n_perm)
        Surrogate brain maps generated by make_surrogates().

    Returns
    -------
    p_value : float
        Spin-test (permutation-based) p-value.
    """

    emp, _ = get_reg_r_sq(X, y) # Empirical adjusted R²
    nspins = surrogates.shape[1]
    null = np.zeros((nspins, ))

    # Compute adjusted R² for each surrogate
    for s in range(nspins):
        null[s], _ = get_reg_r_sq(X, surrogates[:,s])

    # p-value = fraction of surrogate R² values greater than empirical R²
    return (1 + sum(null > emp))/(nspins + 1)